export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const GET_MY_POST_START = 'GET_MY_POST_START';
export const GET_MY_POST_SUCCESS = 'GET_MY_POST_SUCCESS';
export const GET_MY_POST_FAILURE = 'GET_MY_POST_FAILURE';

export const GET_TIMELINE_POST_START = 'GET_TIMELINE_POST_START';
export const GET_TIMELINE_POST_SUCCESS = 'GET_TIMELINE_POST_SUCCESS';
export const GET_TIMELINE_POST_FAILURE = 'GET_TIMELINE_POST_FAILURE';